-- ============================================================================
-- 20260923094700_proformas_con_prendas.sql — Proformas con prendas del catálogo (ADR-0167)
--
-- EL PROBLEMA. Hasta hoy una proforma era un total suelto: una sola línea «Venta» con un monto escrito a
-- mano. No decía qué prendas se cotizaron, y convertirla (`convertir_proforma_a_comprobante`, 0010) creaba
-- un comprobante SIN venta ni movimiento de stock: con prendas reales, la clienta se llevaría ropa sin que
-- el inventario bajara. Además guardaba el total CON IGV en `precio_unitario`, que para una línea sin prenda
-- se lee SIN IGV: al convertir, el comprobante declaraba un 18 % de más.
--
-- ANALOGÍA CAYLA. Es la hoja que la encargada le entrega a la clienta con lo que se probó, prenda por prenda,
-- y el precio que se le guarda unos días. Cuando vuelve, no se «convierte» la hoja en boleta: se cobra en la
-- caja como cualquier venta (baja el stock, entra a caja, sale la boleta) y la hoja se marca como cobrada.
--
-- DECISIONES (Felipe, 2026-09-22 — docs/superpowers/specs/2026-09-22-proformas-con-prendas-design.md):
--   · Se cobra en el Punto de Venta (registrar_venta) y después `marcar_proforma_cobrada` la enlaza.
--   · No reserva stock: congela el precio, no la prenda.
--   · Descuento por línea hasta 20 %, con motivo de la lista de registrar_venta.
--   · La base copia la descripción y el código de cada prenda y calcula ella el total.
-- ============================================================================

-- ---------- Columnas ----------
-- Número propio («PRO-000123»): las proformas existentes lo reciben al agregar la columna.
alter table retail.proformas add column if not exists numero bigint generated by default as identity;
alter table retail.proformas drop constraint if exists proformas_numero_unico;
alter table retail.proformas add constraint proformas_numero_unico unique (numero);
alter table retail.proformas add column if not exists nota text;
alter table retail.proformas drop constraint if exists proformas_nota_largo;
alter table retail.proformas add constraint proformas_nota_largo check (nota is null or char_length(nota) <= 500);
alter table retail.proformas add column if not exists venta_id uuid references retail.ventas(id);

-- ---------- crear_proforma v2 ----------
-- La firma vieja recibía subtotal/igv/total de la pantalla. Se BORRA en esta misma migración: dos
-- sobrecargas vivas ya tumbaron una pantalla (PostgREST no sabe cuál elegir, 2026-09-21).
drop function if exists retail.crear_proforma(uuid, jsonb, numeric, numeric, numeric, text, text, timestamptz);

create function retail.crear_proforma(
  p_ubicacion_id uuid,
  p_items jsonb,
  p_cliente_nombre text default null,
  p_cliente_num_doc text default null,
  p_vence_at timestamptz default null,
  p_nota text default null
) returns uuid
language plpgsql
security definer
set search_path = retail, public, extensions
as $$
declare
  v_id uuid; v_persona uuid; v_item jsonb; v_lineas jsonb := '[]'::jsonb;
  v_precio numeric; v_activo boolean; v_descripcion text; v_codigo text;
  v_cantidad integer; v_descuento numeric; v_motivo text; v_detalle text;
  v_total numeric := 0; v_igv numeric;
begin
  if not fn_puede_operar_ubicacion(p_ubicacion_id) then
    raise exception 'No tienes permiso para crear proformas en esa ubicación' using errcode = '42501';
  end if;
  if p_items is null or jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
    raise exception 'La proforma necesita al menos una prenda';
  end if;

  for v_item in select * from jsonb_array_elements(p_items) loop
    v_precio := null;
    select v.precio, v.activo, concat_ws(' · ', p.referencia, t.valor, c.nombre), v.codigo
      into v_precio, v_activo, v_descripcion, v_codigo
      from variantes v
      join productos p on p.id = v.producto_id
      left join tallas t on t.id = v.talla_id
      left join colores c on c.codigo = v.color_codigo
     where v.id = (v_item ->> 'variante_id')::uuid;
    if v_precio is null or not v_activo then
      raise exception 'proforma_prenda_no_disponible' using detail = coalesce(v_descripcion, v_item ->> 'variante_id', '(sin prenda)');
    end if;

    if (v_item ->> 'cantidad') is null or (v_item ->> 'cantidad')::numeric <= 0
       or (v_item ->> 'cantidad')::numeric <> trunc((v_item ->> 'cantidad')::numeric) then
      raise exception 'La cantidad de % tiene que ser un entero mayor que 0', v_descripcion;
    end if;
    v_cantidad := (v_item ->> 'cantidad')::integer;

    -- El mismo candado que registrar_venta: el precio de la línea es el de catálogo de HOY.
    if round(coalesce((v_item ->> 'precio_unitario')::numeric, -1), 2) <> round(v_precio, 2) then
      raise exception 'venta_precio_cambiado'
        using detail = v_descripcion,
              hint = format('En catálogo vale S/%s y la pantalla mandó S/%s', v_precio, v_item ->> 'precio_unitario');
    end if;

    v_descuento := round(coalesce((v_item ->> 'descuento_unitario')::numeric, 0), 2);
    v_motivo := nullif(btrim(coalesce(v_item ->> 'motivo_descuento', '')), '');
    v_detalle := nullif(btrim(coalesce(v_item ->> 'motivo_descuento_detalle', '')), '');
    if v_descuento < 0 or v_descuento > round(v_precio * 0.20, 2) + 0.01 then
      raise exception 'proforma_descuento_fuera_de_tope' using detail = v_descripcion,
        hint = 'En la proforma el descuento va de 0 a 20 % por prenda; más que eso lo decide un líder al cobrar.';
    end if;
    if v_descuento > 0 then
      if v_motivo is null or v_motivo <> all (array['cumpleanos_clienta_top', 'prenda_con_desperfecto', 'liquidacion_temporada', 'cerrar_venta', 'otro']) then
        raise exception 'venta_descuento_sin_motivo' using detail = v_descripcion;
      end if;
      if v_motivo = 'otro' and v_detalle is null then
        raise exception 'venta_descuento_sin_motivo' using detail = v_descripcion, hint = 'El motivo «Otro» necesita el detalle.';
      end if;
    else
      v_motivo := null; v_detalle := null;
    end if;

    v_total := v_total + (v_precio - v_descuento) * v_cantidad;
    -- La base copia la descripción y el código: no se cree lo que manda la pantalla.
    v_lineas := v_lineas || jsonb_build_array(jsonb_build_object(
      'variante_id', v_item ->> 'variante_id', 'cantidad', v_cantidad, 'precio_unitario', v_precio,
      'descuento_unitario', v_descuento, 'motivo_descuento', v_motivo, 'motivo_descuento_detalle', v_detalle,
      'descripcion', v_descripcion, 'codigo', v_codigo));
  end loop;

  v_total := round(v_total, 2);
  if v_total <= 0 then
    raise exception 'El total de la proforma tiene que ser mayor que 0';
  end if;
  v_igv := round(v_total - v_total / 1.18, 2);

  select id into v_persona from public.personas where auth_user_id = auth.uid();
  insert into proformas (ubicacion_id, items, subtotal, igv, total, cliente_nombre, cliente_num_doc, usuario_id, vence_at, nota)
    values (p_ubicacion_id, v_lineas, v_total - v_igv, v_igv, v_total,
            nullif(btrim(p_cliente_nombre), ''), nullif(btrim(p_cliente_num_doc), ''), v_persona, p_vence_at,
            nullif(btrim(p_nota), ''))
    returning id into v_id;
  return v_id;
end;
$$;

revoke all on function retail.crear_proforma(uuid, jsonb, text, text, timestamptz, text) from public, anon;
grant execute on function retail.crear_proforma(uuid, jsonb, text, text, timestamptz, text) to authenticated;

-- ---------- marcar_proforma_cobrada ----------
-- Segundo paso del cobro: registrar_venta ya movió stock, caja y comprobante; esto solo enlaza la proforma.
-- Idempotente: el Punto de Venta puede reintentarlo tras un corte de red.
create or replace function retail.marcar_proforma_cobrada(p_proforma_id uuid, p_venta_id uuid)
returns void
language plpgsql
security definer
set search_path = retail, public, extensions
as $$
declare v_proforma proformas%rowtype; v_venta ventas%rowtype;
begin
  select * into v_proforma from proformas where id = p_proforma_id for update;
  if not found then
    raise exception 'La proforma no existe';
  end if;
  if not fn_puede_operar_ubicacion(v_proforma.ubicacion_id) then
    raise exception 'No tienes permiso sobre esa proforma' using errcode = '42501';
  end if;
  if v_proforma.estado = 'convertida' and v_proforma.venta_id = p_venta_id then
    return;
  end if;
  if v_proforma.estado <> 'vigente' then
    raise exception 'La proforma ya no está vigente (está %)', v_proforma.estado;
  end if;
  select * into v_venta from ventas where id = p_venta_id;
  if not found or v_venta.estado <> 'completada' then
    raise exception 'La venta no existe o está anulada';
  end if;
  if v_venta.ubicacion_id <> v_proforma.ubicacion_id then
    raise exception 'La venta es de otra tienda que la proforma';
  end if;
  update proformas set estado = 'convertida', venta_id = p_venta_id where id = p_proforma_id;
end;
$$;

revoke all on function retail.marcar_proforma_cobrada(uuid, uuid) from public, anon;
grant execute on function retail.marcar_proforma_cobrada(uuid, uuid) to authenticated;

-- ---------- convertir_proforma_a_comprobante: fuera de la pantalla ----------
-- Crea un comprobante sin venta ni stock y arrastra el error de IGV. No se borra (historia): se le quita el
-- permiso para que nadie la llame desde la app.
revoke execute on function retail.convertir_proforma_a_comprobante from public, anon, authenticated;
